spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhu.authoritymanagement.entity
logging:
  level:
    com.zhu.authoritymanagement.mapper: trace